# Obsidian Post-Processor V2 Configuration
# Save this to config.yaml and customize for your vault

vault_path: "/Users/wese/Repos/obsidian-postprocessor/testvault/test-vault"

# Exclusion patterns (glob syntax)
exclude_patterns:
  - "**/*.sync-conflict*"
  - "templates/**"
  - "archive/**"
  - "**/*.template.md"
  - "**/.*"  # Hidden files

# Processing configuration
processing:
  concurrency_limit: 1
  retry_attempts: 3
  retry_delay: 1.0
  timeout: 300

# Processor definitions
processors:
  transcribe:
    type: "custom_api"
    config:
      api_url: "https://whisper.nas.nope.at/transcribe"
      timeout: 300
      model: "medium"
      language: "auto"

  # Example custom script processor
  # custom_script:
  #   type: "script"
  #   config:
  #     command: "python scripts/custom.py {audio_file} {note_file}"
  #     timeout: 120

# Logging configuration
logging:
  level: "INFO"
  file: "logs/processor.log"
  format: "structured"
